version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure
